# Generated by Django 3.0.1 on 2020-01-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('image_url', models.URLField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
