# Generated by Django 3.0.1 on 2020-01-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200102_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('bio', models.CharField(default='', max_length=300)),
                ('email', models.TextField(default='')),
                ('image_url', models.URLField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInformation',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
