# Generated by Django 3.0.1 on 2020-01-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200102_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='bio',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
