# Generated by Django 3.0.1 on 2020-01-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200102_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
