# Generated by Django 3.0.1 on 2020-01-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200102_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='bio',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
