# Generated by Django 3.0.1 on 2020-01-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200103_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
